definitions:
  model.CreateItemsRequest:
    properties:
      description:
        type: string
      guid:
        type: string
      item_name:
        type: string
    required:
    - description
    - guid
    - item_name
    type: object
  model.ExpensePeriod:
    properties:
      fromdate:
        type: string
      item:
        type: string
      todate:
        type: string
    type: object
  model.UserExpense:
    properties:
      amount:
        type: number
      date:
        type: string
      id:
        type: integer
      item:
        type: string
      item_id:
        type: integer
    type: object
externalDocs:
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact: {}
  description: This is an items API
  termsOfService: http://swagger.io/terms/
  title: Booker Api
  version: "1.0"
paths:
  /book_cost_items/create:
    post:
      description: Create new items data in Db.
      parameters:
      - description: Query Params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateItemsRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
      summary: Create items
      tags:
      - items
  /book_cost_items/delete/{id}:
    delete:
      description: Delete items data from Db.
      parameters:
      - description: Enter item_id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
      summary: Delete item by id
      tags:
      - items
  /book_cost_items/get_all:
    get:
      description: Get all items recorded to DB
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
      summary: Get all items
      tags:
      - items
  /book_cost_items/get_only_one/{id}:
    get:
      description: Get Items By Id
      parameters:
      - description: Enter item_id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
      summary: Get Items By Id
      tags:
      - items
  /book_cost_items/update/{id}:
    post:
      description: Update items data in Db.
      parameters:
      - description: Enter id
        in: path
        name: id
        required: true
        type: string
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateItemsRequest'
      produces:
      - application/json
      responses:
        "20":
          description: ""
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
      summary: Update Items
      tags:
      - items
  /book_daily_expense/create:
    post:
      description: Expense Create
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.UserExpense'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
      summary: Expense Create
      tags:
      - expense
  /book_daily_expense/get_by_date_and_item:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
      tags:
      - expense
  /book_daily_expense/get_by_id/{id}:
    get:
      description: Get Expense By Item
      parameters:
      - description: enter item_id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
      summary: Get Expense By Item
      tags:
      - expense
  /book_daily_expense/get_summ_by_period:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
      tags:
      - expense
  /daily_expense/get_by_date:
    get:
      description: Get Expense By date
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ExpensePeriod'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
      summary: Get Expense By date
      tags:
      - expense
swagger: "2.0"
