definitions:
  model.UserCostItems:
    properties:
      code:
        type: integer
      description:
        type: string
      id:
        type: integer
      item_name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is an items API
  termsOfService: http://swagger.io/terms/
  title: Booker Api
  version: "1.0"
paths:
  /cost_items/create_items:
    post:
      description: Save items data in Db.
      parameters:
      - description: Create items
        in: body
        name: tags
        required: true
        schema:
          $ref: '#/definitions/model.UserCostItems'
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: Create items
      tags:
      - tags
swagger: "2.0"
